## Sentiment Analysis
## Bret Young
### 5 April 2020

In [1]:
# Analyzing text for whether comments are positive or negative

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

Addr1='/Users/bretyoung/Desktop/DSC 550/week-4/DailyComments.csv'
dataframe = pd.read_csv(Addr1)
print(dataframe)
corpus = dataframe['comments']

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print("")
print("vectorized words")
print("")
print(vectorizer.get_feature_names())
print("")
print("Identify Feature Words - Matrix View")
print("")
print( X.toarray())

df = pd.DataFrame({'text' : corpus})

# check for positive words and negative words
df['positive1'] = df.text.str.count('good')
df['positive2']= df.text.str.count('special')
df['negative'] = df.text.str.count('bad')
df['TotScore'] = df.positive1 + df.positive2 - df.negative

print("")
print(df)

Z = sum(df['TotScore'])
print("")
print("Overall Score:  ",Z)


  Day of Week                                        comments
0      Monday                             Hello, how are you?
1     Tuesday                            Today is a good day!
2   Wednesday  It's my birthday so it's a really special day!
3    Thursday       Today is neither a good day or a bad day!
4      Friday                           I'm having a bad day.
5    Saturday       There' s nothing special happening today.
6      Sunday                      Today is a SUPER good day!

vectorized words

['are', 'bad', 'birthday', 'day', 'good', 'happening', 'having', 'hello', 'how', 'is', 'it', 'my', 'neither', 'nothing', 'or', 'really', 'so', 'special', 'super', 'there', 'today', 'you']

Identify Feature Words - Matrix View

[[1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 0 0 0 2 1 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 2 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0]
 [0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0

A scenario where one might be interested in determining if texit is positive or negative is when parsing reviews. I have choosen a dataset from Kaggle.com on Women’s Clothing E-Commerce reviews. We will look at the reviews and determine if the review is positive, neutral or negative.

In [2]:
# Analyzing text for whether comments are positive or negative

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

Addr1='/Users/bretyoung/Desktop/DSC 550/Womens Clothing E-Commerce Reviews.csv'
dataframe = pd.read_csv(Addr1)
print(dataframe)
corpus = dataframe['Review Text'].dropna()

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print("")
print("vectorized words")
print("")
print(vectorizer.get_feature_names())
print("")
print("Identify Feature Words - Matrix View")
print("")
print( X.toarray())

df = pd.DataFrame({'text' : corpus})

       Unnamed: 0  Clothing ID  Age  \
0               0          767   33   
1               1         1080   34   
2               2         1077   60   
3               3         1049   50   
4               4          847   47   
...           ...          ...  ...   
23481       23481         1104   34   
23482       23482          862   48   
23483       23483         1104   31   
23484       23484         1084   28   
23485       23485         1104   52   

                                                   Title  \
0                                                    NaN   
1                                                    NaN   
2                                Some major design flaws   
3                                       My favorite buy!   
4                                       Flattering shirt   
...                                                  ...   
23481                     Great dress for many occasions   
23482                         Wish it was made of c

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [3]:
# a list of positive and negative words were found here: 
# https://github.com/shekhargulati/sentiment-analysis-python/blob/master/opinion-lexicon-English/positive-words.txt

file_pos = open('/Users/bretyoung/Desktop/DSC 550/positive-words.txt', 'r')


# create a list of positive words
positive_list = file_pos.read().split('\n')
positive_list = positive_list[35:]
print(positive_list)

['a+', 'abound', 'abounds', 'abundance', 'abundant', 'accessable', 'accessible', 'acclaim', 'acclaimed', 'acclamation', 'accolade', 'accolades', 'accommodative', 'accomodative', 'accomplish', 'accomplished', 'accomplishment', 'accomplishments', 'accurate', 'accurately', 'achievable', 'achievement', 'achievements', 'achievible', 'acumen', 'adaptable', 'adaptive', 'adequate', 'adjustable', 'admirable', 'admirably', 'admiration', 'admire', 'admirer', 'admiring', 'admiringly', 'adorable', 'adore', 'adored', 'adorer', 'adoring', 'adoringly', 'adroit', 'adroitly', 'adulate', 'adulation', 'adulatory', 'advanced', 'advantage', 'advantageous', 'advantageously', 'advantages', 'adventuresome', 'adventurous', 'advocate', 'advocated', 'advocates', 'affability', 'affable', 'affably', 'affectation', 'affection', 'affectionate', 'affinity', 'affirm', 'affirmation', 'affirmative', 'affluence', 'affluent', 'afford', 'affordable', 'affordably', 'afordable', 'agile', 'agilely', 'agility', 'agreeable', 'ag

In [4]:
file_neg = open('/Users/bretyoung/Desktop/DSC 550/negative-words.txt', 'r',encoding="ISO-8859-1")

# create a list of negative words
negative_list = file_neg.read().split('\n')
negative_list = negative_list[35:]
print(negative_list)

['2-faced', '2-faces', 'abnormal', 'abolish', 'abominable', 'abominably', 'abominate', 'abomination', 'abort', 'aborted', 'aborts', 'abrade', 'abrasive', 'abrupt', 'abruptly', 'abscond', 'absence', 'absent-minded', 'absentee', 'absurd', 'absurdity', 'absurdly', 'absurdness', 'abuse', 'abused', 'abuses', 'abusive', 'abysmal', 'abysmally', 'abyss', 'accidental', 'accost', 'accursed', 'accusation', 'accusations', 'accuse', 'accuses', 'accusing', 'accusingly', 'acerbate', 'acerbic', 'acerbically', 'ache', 'ached', 'aches', 'achey', 'aching', 'acrid', 'acridly', 'acridness', 'acrimonious', 'acrimoniously', 'acrimony', 'adamant', 'adamantly', 'addict', 'addicted', 'addicting', 'addicts', 'admonish', 'admonisher', 'admonishingly', 'admonishment', 'admonition', 'adulterate', 'adulterated', 'adulteration', 'adulterier', 'adversarial', 'adversary', 'adverse', 'adversity', 'afflict', 'affliction', 'afflictive', 'affront', 'afraid', 'aggravate', 'aggravating', 'aggravation', 'aggression', 'aggress

In [14]:
# loop through words to see if they are in positive or negative lists

df['positive'] = 0 
df['negative'] = 0
df['TotScore'] = 0

for i in range(0, len(df)):
    try:
        for j in df.text.str.split()[i]:
            if j in positive_list:
                df.positive[i] += 1 # add 1 for each positive word
            elif j in negative_list:
                df.negative[i] += 1 # add 1 for each negative word
    except KeyError:
         continue
    df.TotScore[i] = df.positive[i] - df.negative[i] # total positive minus negative

print(df)

Z = sum(df.TotScore)

print("")
print("Overall Score: ",Z)



/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pa

                                                    text  positive  negative  \
0      Absolutely wonderful - silky and sexy and comf...         3         0   
1      Love this dress!  it's sooo pretty.  i happene...         2         0   
2      I had such high hopes for this dress and reall...         3         3   
3      I love, love, love this jumpsuit. it's fun, fl...         2         0   
4      This shirt is very flattering to all due to th...         5         0   
...                                                  ...       ...       ...   
23481  I was very happy to snag this dress at such a ...         0         0   
23482  It reminds me of maternity clothes. soft, stre...         0         0   
23483  This fit well, but the top was very see throug...         0         0   
23484  I bought this dress for a wedding i have this ...         0         0   
23485  This dress in a lovely platinum is feminine an...         0         0   

       TotScore  
0             3  
1  